# Generated by Django 4.2.5 on 2023-10-15 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=14)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Minhas Classes',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('data_nascimento', models.DateField()),
                ('restricao_alimentar', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('adulto', 'Adulto'), ('crianca', 'Criança')], max_length=10)),
                ('conhecidos_cetec', models.CharField(choices=[('aluno', 'Aluno'), ('aluno_tecnico', 'Aluno do Técnico'), ('professor', 'Professor'), ('ninguem', 'Ninguém')], max_length=15)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.buy')),
            ],
            options={
                'verbose_name_plural': 'Tickets',
            },
        ),
    ]
