# Generated by Django 4.2.5 on 2023-10-15 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buy',
            options={'verbose_name_plural': 'Compradores'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name_plural': 'Ingressos'},
        ),
        migrations.RenameField(
            model_name='buy',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='name',
            new_name='nome',
        ),
    ]
